//! Idiomatic, safe representation of a gzip header (RFC 1952).
//!
//! This module defines [`GzHeader`], the owned, memory-safe Rust equivalent of
//! the C `gz_header` structure declared in `zlib.h` (fields `text`, `time`,
//! `xflags`, `os`, `extra`/`extra_len`/`extra_max`, `name`/`name_max`,
//! `comment`/`comm_max`, `hcrc`, and `done`). It carries the metadata that is
//! written into a gzip member header by [`deflateSetHeader`] and read back out
//! of one by [`inflateGetHeader`].
//!
//! # Relationship to the C API
//!
//! The C `gz_header` uses raw `Bytef *` pointers paired with explicit length
//! and capacity fields (`extra_len`/`extra_max`, `name_max`, `comm_max`). Those
//! raw-pointer, manual-length concerns belong exclusively to the FFI boundary
//! ([`crate::ffi`], `src/ffi/types.rs`), which mirrors this type as a
//! `#[repr(C)]` struct and performs a straightforward, lossless conversion:
//!
//! | C `gz_header` field                | Rust [`GzHeader`] field      |
//! |------------------------------------|------------------------------|
//! | `int text`                         | [`text`](GzHeader::text): `bool`               |
//! | `uLong time`                       | [`time`](GzHeader::time): `u32`                |
//! | `int xflags`                       | [`xflags`](GzHeader::xflags): `i32`            |
//! | `int os`                           | [`os`](GzHeader::os): `i32`                    |
//! | `Bytef *extra`                     | [`extra`](GzHeader::extra): `Option<Vec<u8>>`  |
//! | `uInt extra_len`                   | [`extra_len`](GzHeader::extra_len): `u32`      |
//! | `uInt extra_max`                   | [`extra_max`](GzHeader::extra_max): `u32`      |
//! | `Bytef *name`                      | [`name`](GzHeader::name): `Option<Vec<u8>>`    |
//! | `uInt name_max`                    | [`name_max`](GzHeader::name_max): `u32`        |
//! | `Bytef *comment`                   | [`comment`](GzHeader::comment): `Option<Vec<u8>>` |
//! | `uInt comm_max`                    | [`comm_max`](GzHeader::comm_max): `u32`        |
//! | `int hcrc`                         | [`hcrc`](GzHeader::hcrc): `bool`               |
//! | `int done`                         | [`done`](GzHeader::done): `bool`               |
//!
//! A `Z_NULL` C pointer maps to [`None`]; a non-null pointer with an associated
//! length maps to `Some(Vec<u8>)`. C `int` booleans (`0`/non-zero) map to Rust
//! [`bool`].
//!
//! # Conventions and design decisions
//!
//! * **No trailing NUL.** The gzip file format terminates the `name` and
//!   `comment` fields with a zero byte (RFC 1952 §2.3.1). [`GzHeader`] stores
//!   the payload bytes *without* that terminating NUL. Two distinct consumers
//!   restore it, and they must not be confused:
//!   * **Writing a gzip stream.** The deflate encoder's `Name` and `Comment`
//!     header phases (`src/deflate/mod.rs`) emit the stored bytes and then a
//!     `0` past their end, reproducing C's "copy the C string including its
//!     terminator" loop. Termination of the *wire format* is the encoder's job.
//!   * **Converting a C `gz_header`.** The FFI boundary (`src/ffi/types.rs`)
//!     translates between this owned type and the caller's raw `Bytef *`
//!     fields: it reads a caller pointer as a NUL-terminated C string and
//!     drops the terminator, and when writing back into a caller-supplied
//!     buffer it NUL-terminates within `name_max`/`comm_max`. That is C-string
//!     marshalling, not gzip framing.
//! * **`done` is a `bool` here.** The C field is tri-state: `inflateGetHeader`
//!   sets it to `1` when the header is fully parsed and to `-1` when the stream
//!   turns out to be a raw zlib stream with no gzip header. That `-1` sentinel
//!   is a boundary concern surfaced in `src/ffi/types.rs`; the idiomatic type
//!   models only the "header fully read" flag as a [`bool`].
//! * **Read-only capacities.** [`extra_max`](GzHeader::extra_max),
//!   [`name_max`](GzHeader::name_max), and [`comm_max`](GzHeader::comm_max)
//!   bound how many bytes `inflateGetHeader` will store into the respective
//!   fields while *reading* a header. They are ignored when *writing* a header
//!   with `deflateSetHeader`, and default to `0`.
//!
//! # Examples
//!
//! Build a header to be written with `deflateSetHeader`:
//!
//! ```
//! use zlib_rs::GzHeader;
//!
//! let header = GzHeader::new()
//!     .with_name(b"example.txt".to_vec())
//!     .with_comment(b"generated by zlib-rs".to_vec())
//!     .with_time(1_700_000_000)
//!     .with_os(255) // 255 == "unknown" per RFC 1952
//!     .with_text(true);
//!
//! assert_eq!(header.name.as_deref(), Some(&b"example.txt"[..]));
//! assert!(header.text);
//! assert!(!header.done);
//! ```
//!
//! [`deflateSetHeader`]: https://www.zlib.net/manual.html
//! [`inflateGetHeader`]: https://www.zlib.net/manual.html

use alloc::vec::Vec;

/// Gzip header information exchanged with the deflate/inflate engines.
///
/// `GzHeader` is the idiomatic, owned, fully safe counterpart of the C
/// `gz_header` struct (`zlib.h`). It is used in two directions:
///
/// * **Writing** (`deflateSetHeader`): the caller populates [`text`],
///   [`time`], [`os`], [`extra`], [`name`], [`comment`], and [`hcrc`], and the
///   deflate engine serializes them into the gzip member header. Note that
///   [`xflags`] is *ignored* when writing — the encoder derives the gzip `XFL`
///   byte from the compression level.
/// * **Reading** (`inflateGetHeader`): the inflate engine fills the fields in
///   from a parsed gzip header, honoring the [`extra_max`], [`name_max`], and
///   [`comm_max`] capacity limits, and sets [`done`] to `true` once the header
///   is complete.
///
/// See RFC 1952 for the authoritative definition of each gzip header field.
///
/// [`text`]: GzHeader::text
/// [`time`]: GzHeader::time
/// [`os`]: GzHeader::os
/// [`extra`]: GzHeader::extra
/// [`name`]: GzHeader::name
/// [`comment`]: GzHeader::comment
/// [`hcrc`]: GzHeader::hcrc
/// [`xflags`]: GzHeader::xflags
/// [`extra_max`]: GzHeader::extra_max
/// [`name_max`]: GzHeader::name_max
/// [`comm_max`]: GzHeader::comm_max
/// [`done`]: GzHeader::done
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GzHeader {
    /// `true` if the compressed data is believed to be text.
    ///
    /// Mirrors C `gz_header.text` and the gzip `FLG.FTEXT` bit (RFC 1952).
    pub text: bool,

    /// Modification time (gzip `MTIME`), in seconds since the Unix epoch.
    ///
    /// Mirrors C `gz_header.time`. The gzip `MTIME` field is 32 bits wide, so
    /// this is a [`u32`] (the C API widens it to `uLong`). A value of `0`
    /// means "no timestamp available".
    pub time: u32,

    /// Extra flags (gzip `XFL`, RFC 1952).
    ///
    /// Mirrors C `gz_header.xflags`. Populated when *reading* a header. It is
    /// **ignored when writing**: the deflate encoder sets the `XFL` byte from
    /// the compression level.
    pub xflags: i32,

    /// Operating-system code (gzip `OS`, RFC 1952 §2.3.1).
    ///
    /// Mirrors C `gz_header.os`. RFC 1952 reserves the value `255` for
    /// "unknown".
    ///
    /// Three cases determine what actually reaches the wire:
    ///
    /// * **No header installed.** With no `deflateSetHeader` call the encoder
    ///   writes [`crate::util::OS_CODE`], the platform value C's `zutil.h`
    ///   cascade selects for the same target — `10` on Windows, `19` on Apple,
    ///   `3` (Unix) everywhere else. Reference zlib writes exactly the same byte
    ///   on the same platform, so this is what keeps gzip output byte-identical;
    ///   a hard-coded `3` would diverge from a Windows- or macOS-built `libz`.
    /// * **A header installed.** The encoder writes the low byte of this field
    ///   verbatim (`os & 0xff`), whatever it holds.
    /// * **A default-constructed header.** [`GzHeader::new`] and
    ///   [`GzHeader::default`] leave this field at `0`, so installing one
    ///   unmodified emits `0` (FAT filesystem / MS-DOS), *not* `3` and not
    ///   `255`. Call [`with_os`](GzHeader::with_os) to choose deliberately —
    ///   `with_os(255)` for "unknown".
    ///
    /// When *reading* a header, `inflateGetHeader` stores whatever byte the
    /// stream carried.
    pub os: i32,

    /// Optional gzip "extra" subfield block (`FEXTRA`, RFC 1952).
    ///
    /// Corresponds to the C `gz_header.extra` pointer: [`None`] is a `Z_NULL`
    /// pointer (no extra field), while `Some(bytes)` holds the extra-field bytes
    /// actually stored. When *reading*, that may be **fewer** bytes than the
    /// stream declared — see [`extra_len`](GzHeader::extra_len).
    pub extra: Option<Vec<u8>>,

    /// The extra field's **declared** length, in bytes.
    ///
    /// Mirrors C `gz_header.extra_len`, which this crate keeps as a distinct
    /// field rather than inferring it from `extra.len()` because the two are not
    /// the same number:
    ///
    /// * **Reading** (`inflateGetHeader`): set to the full 16-bit `XLEN` the gzip
    ///   header declared (`inflate.c` L599-L600 writes it unconditionally
    ///   whenever a header is installed, *before* and independently of any copy).
    ///   The copy into [`extra`](GzHeader::extra) is separately clamped to
    ///   [`extra_max`](GzHeader::extra_max) (`inflate.c` L614-L621), so when the
    ///   caller's buffer is too small this field still reports the true length
    ///   while `extra` holds only the leading `extra_max` bytes.
    ///
    ///   `extra_len > extra_max` is therefore the caller's **only** signal that
    ///   the extra field was truncated, exactly as `zlib.h` specifies for
    ///   `inflateGetHeader`: once `done` is true, `extra_len` contains the actual
    ///   extra field length, and `extra` contains that field *or that field
    ///   truncated if `extra_max` is less than `extra_len`*. It is also written
    ///   for the documented length-query pattern, where the caller leaves
    ///   `extra` as [`None`] (C `Z_NULL`) purely to learn the length.
    ///
    ///   Because C writes it only when the header actually carries an `FEXTRA`
    ///   field, a stream **without** one leaves whatever value the caller had
    ///   already placed here untouched.
    /// * **Writing** (`deflateSetHeader`): **ignored.** The encoder emits
    ///   `extra.len()` bytes from [`extra`](GzHeader::extra), so the `Vec` is the
    ///   single source of truth on the write path and this field cannot desynchronize
    ///   the emitted header. At the C boundary the two agree by construction: the
    ///   caller's `extra_len` bytes are what get read out of their `extra` pointer
    ///   into the `Vec`.
    ///
    /// Defaults to `0`.
    pub extra_len: u32,

    /// Optional original file name (`FNAME`, RFC 1952).
    ///
    /// Mirrors C `gz_header.name`. [`None`] corresponds to `Z_NULL`. The bytes
    /// are stored **without** the trailing NUL terminator that appears in the
    /// on-disk gzip format; the FFI layer adds/removes it during conversion.
    pub name: Option<Vec<u8>>,

    /// Optional human-readable comment (`FCOMMENT`, RFC 1952).
    ///
    /// Mirrors C `gz_header.comment`. [`None`] corresponds to `Z_NULL`. As with
    /// [`name`](GzHeader::name), the bytes are stored **without** the trailing
    /// NUL terminator.
    pub comment: Option<Vec<u8>>,

    /// `true` if a header CRC-16 is (or will be) present (`FHCRC`, RFC 1952).
    ///
    /// Mirrors C `gz_header.hcrc`. When writing, requests that a header CRC be
    /// emitted; when reading, indicates that one was present.
    pub hcrc: bool,

    /// `true` once the gzip header has been fully parsed while reading.
    ///
    /// Mirrors C `gz_header.done`. `inflateGetHeader` sets this to `true` when
    /// the header is complete. (The C field additionally uses `-1` to signal a
    /// raw zlib stream with no gzip header; that tri-state is represented only
    /// at the FFI boundary in `src/ffi/types.rs`.) Unused when writing.
    pub done: bool,

    /// Read capacity for [`extra`](GzHeader::extra), in bytes.
    ///
    /// Mirrors C `gz_header.extra_max`. Bounds how many bytes
    /// `inflateGetHeader` will store into `extra` while reading a header.
    /// Ignored when writing; defaults to `0`.
    pub extra_max: u32,

    /// Read capacity for [`name`](GzHeader::name), in bytes.
    ///
    /// Mirrors C `gz_header.name_max`. Bounds how many bytes (including the
    /// terminating NUL, in the C accounting) `inflateGetHeader` will store into
    /// `name` while reading a header. Ignored when writing; defaults to `0`.
    pub name_max: u32,

    /// Read capacity for [`comment`](GzHeader::comment), in bytes.
    ///
    /// Mirrors C `gz_header.comm_max`. Bounds how many bytes (including the
    /// terminating NUL, in the C accounting) `inflateGetHeader` will store into
    /// `comment` while reading a header. Ignored when writing; defaults to `0`.
    pub comm_max: u32,
}

impl GzHeader {
    /// Creates a new, empty `GzHeader`.
    ///
    /// This is equivalent to [`GzHeader::default`]: every optional field is
    /// [`None`], the boolean flags ([`text`](GzHeader::text),
    /// [`hcrc`](GzHeader::hcrc), [`done`](GzHeader::done)) are `false`, and all
    /// numeric fields (including [`os`](GzHeader::os)) are `0`.
    ///
    /// # Examples
    ///
    /// ```
    /// use zlib_rs::GzHeader;
    ///
    /// let header = GzHeader::new();
    /// assert_eq!(header, GzHeader::default());
    /// assert!(header.name.is_none());
    /// ```
    #[must_use]
    #[inline]
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets the [`text`](GzHeader::text) flag and returns the updated header.
    ///
    /// # Examples
    ///
    /// ```
    /// use zlib_rs::GzHeader;
    ///
    /// let header = GzHeader::new().with_text(true);
    /// assert!(header.text);
    /// ```
    #[must_use]
    #[inline]
    pub fn with_text(mut self, text: bool) -> Self {
        self.text = text;
        self
    }

    /// Sets the modification [`time`](GzHeader::time) and returns the updated
    /// header.
    ///
    /// # Examples
    ///
    /// ```
    /// use zlib_rs::GzHeader;
    ///
    /// let header = GzHeader::new().with_time(1_700_000_000);
    /// assert_eq!(header.time, 1_700_000_000);
    /// ```
    #[must_use]
    #[inline]
    pub fn with_time(mut self, time: u32) -> Self {
        self.time = time;
        self
    }

    /// Sets the operating-system code [`os`](GzHeader::os) and returns the
    /// updated header.
    ///
    /// Pass `255` for the RFC 1952 "unknown" operating system.
    ///
    /// # Examples
    ///
    /// ```
    /// use zlib_rs::GzHeader;
    ///
    /// let header = GzHeader::new().with_os(255);
    /// assert_eq!(header.os, 255);
    /// ```
    #[must_use]
    #[inline]
    pub fn with_os(mut self, os: i32) -> Self {
        self.os = os;
        self
    }

    /// Sets the file [`name`](GzHeader::name) and returns the updated header.
    ///
    /// The provided bytes should **not** include a trailing NUL terminator; the
    /// deflate encoder appends the RFC 1952 terminator when it writes the gzip
    /// header (and the FFI boundary appends one when marshalling this field
    /// back into a caller's C `gz_header` buffer).
    ///
    /// # Examples
    ///
    /// ```
    /// use zlib_rs::GzHeader;
    ///
    /// let header = GzHeader::new().with_name(b"example.txt".to_vec());
    /// assert_eq!(header.name.as_deref(), Some(&b"example.txt"[..]));
    /// ```
    #[must_use]
    #[inline]
    pub fn with_name(mut self, name: impl Into<Vec<u8>>) -> Self {
        self.name = Some(name.into());
        self
    }

    /// Sets the [`comment`](GzHeader::comment) and returns the updated header.
    ///
    /// The provided bytes should **not** include a trailing NUL terminator; the
    /// deflate encoder appends the RFC 1952 terminator when it writes the gzip
    /// header (and the FFI boundary appends one when marshalling this field
    /// back into a caller's C `gz_header` buffer).
    ///
    /// # Examples
    ///
    /// ```
    /// use zlib_rs::GzHeader;
    ///
    /// let header = GzHeader::new().with_comment(b"hello".to_vec());
    /// assert_eq!(header.comment.as_deref(), Some(&b"hello"[..]));
    /// ```
    #[must_use]
    #[inline]
    pub fn with_comment(mut self, comment: impl Into<Vec<u8>>) -> Self {
        self.comment = Some(comment.into());
        self
    }

    /// Sets the [`extra`](GzHeader::extra) subfield block and returns the
    /// updated header.
    ///
    /// The gzip "extra" field is opaque, length-prefixed binary data (RFC 1952
    /// `FEXTRA`). [`extra_len`](GzHeader::extra_len) is set to match the stored
    /// vector's length, keeping the pair self-consistent — which is what a caller
    /// round-tripping a header through `deflateSetHeader` needs. (The encoder
    /// emits `extra.len()` bytes regardless, so this is for the caller's benefit
    /// rather than the wire format's.)
    ///
    /// # Examples
    ///
    /// ```
    /// use zlib_rs::GzHeader;
    ///
    /// let header = GzHeader::new().with_extra(vec![0x01, 0x02, 0x03]);
    /// assert_eq!(header.extra.as_deref(), Some(&[0x01, 0x02, 0x03][..]));
    /// assert_eq!(header.extra_len, 3);
    /// ```
    #[must_use]
    #[inline]
    pub fn with_extra(mut self, extra: impl Into<Vec<u8>>) -> Self {
        let extra = extra.into();
        self.extra_len = extra.len() as u32;
        self.extra = Some(extra);
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_is_empty_header() {
        let header = GzHeader::default();

        // All optional fields are absent (equivalent to C `Z_NULL`).
        assert_eq!(header.extra, None);
        assert_eq!(header.name, None);
        assert_eq!(header.comment, None);

        // Boolean flags start cleared.
        assert!(!header.text);
        assert!(!header.hcrc);
        assert!(!header.done);

        // Numeric fields start at zero, including `os` and the read capacities.
        assert_eq!(header.time, 0);
        assert_eq!(header.xflags, 0);
        assert_eq!(header.os, 0);
        assert_eq!(header.extra_max, 0);
        assert_eq!(header.name_max, 0);
        assert_eq!(header.comm_max, 0);
    }

    #[test]
    fn new_matches_default() {
        assert_eq!(GzHeader::new(), GzHeader::default());
    }

    #[test]
    fn builders_round_trip_field_values() {
        let header = GzHeader::new()
            .with_text(true)
            .with_time(1_700_000_000)
            .with_os(255)
            .with_name(b"example.txt".to_vec())
            .with_comment(b"a comment".to_vec())
            .with_extra(vec![0xDE, 0xAD, 0xBE, 0xEF]);

        assert!(header.text);
        assert_eq!(header.time, 1_700_000_000);
        assert_eq!(header.os, 255);
        assert_eq!(header.name.as_deref(), Some(&b"example.txt"[..]));
        assert_eq!(header.comment.as_deref(), Some(&b"a comment"[..]));
        assert_eq!(header.extra.as_deref(), Some(&[0xDE, 0xAD, 0xBE, 0xEF][..]));

        // Builders that were not called leave defaults intact.
        assert!(!header.hcrc);
        assert!(!header.done);
        assert_eq!(header.xflags, 0);
    }

    #[test]
    fn direct_field_assignment_round_trips() {
        // Fields consumed only when *reading* a header are set directly.
        let mut header = GzHeader::new();
        header.xflags = 4;
        header.hcrc = true;
        header.done = true;
        header.extra_max = 32;
        header.name_max = 64;
        header.comm_max = 128;

        assert_eq!(header.xflags, 4);
        assert!(header.hcrc);
        assert!(header.done);
        assert_eq!(header.extra_max, 32);
        assert_eq!(header.name_max, 64);
        assert_eq!(header.comm_max, 128);
    }

    #[test]
    fn accepts_slice_and_vec_inputs() {
        // `impl Into<Vec<u8>>` accepts both owned vectors and borrowed slices.
        let from_slice = GzHeader::new().with_name(&b"slice"[..]);
        let from_vec = GzHeader::new().with_name(b"slice".to_vec());
        assert_eq!(from_slice, from_vec);
        assert_eq!(from_slice.name.as_deref(), Some(&b"slice"[..]));
    }

    #[test]
    fn empty_extra_is_some_not_none() {
        // An empty-but-present extra field is distinct from an absent one.
        let header = GzHeader::new().with_extra(Vec::new());
        assert_eq!(header.extra.as_deref(), Some(&[][..]));
        assert_ne!(header.extra, None);
    }

    #[test]
    fn clone_and_eq_are_consistent() {
        let header = GzHeader::new()
            .with_name(b"clone.bin".to_vec())
            .with_extra(vec![1, 2, 3])
            .with_text(true);
        let cloned = header.clone();

        assert_eq!(header, cloned);

        // Mutating the clone breaks equality, confirming deep, owned data.
        let mut mutated = cloned;
        mutated.text = false;
        assert_ne!(header, mutated);
    }

    #[test]
    fn debug_impl_is_available() {
        // The derived `Debug` impl must render without panicking.
        let header = GzHeader::new().with_name(b"dbg".to_vec());
        let rendered = alloc::format!("{header:?}");
        assert!(rendered.contains("GzHeader"));
    }
}
